language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - pushd examples/basic && pio run && popd
#    - pio remote -a Canopus test